jwt:
    secret: ideastoituser
spring:
   application:
      name: userapp  
   datasource: 
      driverClassName: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/USER_SERVICE?autoreconnect=true&createDatabaseIfNotExist=true"
      password: "root"
      username: "root"
   profiles:
        active: "dev"
---
spring:
  profiles: dev
---
spring:
  profiles: dev
---
flyway:
   url: jdbc:mysql://localhost:3306/mysql
   schemas: USER_SERVICE
   user: "root"
   password: "root"